version: '3'
services:
  azure-vote-back:
    build: ./azure-vote
    image: scacrforaks.azurecr.io/azure-vote-back:0.1
    container_name: azure-vote-back
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"

  azure-vote-front:
    build: ./azure-vote
    image: scacrforaks.azurecr.io/azure-vote-front:0.1
    container_name: azure-vote-front
    environment:
      REDIS: azure-vote-back
    ports:
        - "8080:80"
